source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'StudyBuddy' do
    pod 'Alamofire', '~> 4.7'
    pod 'GoogleMaps'
    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 1.1.0'
end
